#!/bin/bash
set -e

# Dependency files generated by Circle contain absolute compiler include paths.
# Remove this project's generated files before entering the container so a
# previous macOS/toolchain build cannot be reused by the container toolchain.
docker exec -it circle-dev sh -c '
	rm -f circle/lib/net/httpdaemon.d circle/lib/net/httpdaemon.o
	make -C circle/lib/net CHECK_DEPS=0 httpdaemon.o
	make -C circle/lib/net CHECK_DEPS=0 libnet.a
	rm -f projects/framework/*.d projects/framework/*.o \
		projects/framework/*.elf projects/framework/*.lst \
		projects/framework/*.img projects/framework/*.map
	make -C projects/framework CHECK_DEPS=0
'
cp projects/framework/kernel8-32.img /Volumes/CIRCLE/kernel8-32.img
mkdir -p /Volumes/CIRCLE/www
cp -R projects/framework/www/. /Volumes/CIRCLE/www/
sync
diskutil eject /dev/disk5
